--
-- PostgreSQL database dump
--

\restrict McdhWlN8BZ2uhSymDhaPmVuzeQB2h6ZBr1pZxKSQbxtR5pbHgONC7GFo8BRsSgQ

-- Dumped from database version 16.14 (Ubuntu 16.14-1.pgdg22.04+1)
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_users (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    nombre character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(50) NOT NULL
);


ALTER TABLE public.admin_users OWNER TO postgres;

--
-- Name: admin_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: administradores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.administradores (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    apellido character varying(100) NOT NULL,
    contrasena character varying(255) NOT NULL,
    correo character varying(255) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(100) NOT NULL,
    usuario character varying(100) NOT NULL
);


ALTER TABLE public.administradores OWNER TO postgres;

--
-- Name: administradores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.administradores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administradores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auditoria (
    id bigint NOT NULL,
    accion character varying(100) NOT NULL,
    descripcion character varying(500),
    fecha timestamp(6) without time zone NOT NULL,
    administrador_id bigint NOT NULL
);


ALTER TABLE public.auditoria OWNER TO postgres;

--
-- Name: auditoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auditoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departamentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departamentos (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    descripcion character varying(255),
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.departamentos OWNER TO postgres;

--
-- Name: departamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: empleados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empleados (
    id bigint NOT NULL,
    acceso_permitido boolean NOT NULL,
    activo boolean NOT NULL,
    apellido character varying(100) NOT NULL,
    cargo character varying(100) NOT NULL,
    correo character varying(255) NOT NULL,
    documento character varying(20) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(100) NOT NULL,
    departamento_id bigint NOT NULL
);


ALTER TABLE public.empleados OWNER TO postgres;

--
-- Name: empleados_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empleados ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empleados_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historial_acceso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.historial_acceso (
    id bigint NOT NULL,
    acceso_permitido boolean NOT NULL,
    fecha_ingreso timestamp(6) without time zone NOT NULL,
    fecha_salida timestamp(6) without time zone,
    observaciones character varying(255),
    empleado_id bigint NOT NULL
);


ALTER TABLE public.historial_acceso OWNER TO postgres;

--
-- Name: historial_acceso_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.historial_acceso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_acceso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: intento_acceso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.intento_acceso (
    id bigint NOT NULL,
    exito boolean NOT NULL,
    acceso_date timestamp(6) without time zone NOT NULL,
    message character varying(255),
    empleado_id bigint
);


ALTER TABLE public.intento_acceso OWNER TO postgres;

--
-- Name: intento_acceso_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.intento_acceso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.intento_acceso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: visitantes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.visitantes (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    apellido character varying(100) NOT NULL,
    correo character varying(120),
    documento character varying(30) NOT NULL,
    empresa character varying(255),
    fecha_actualizacion timestamp(6) without time zone,
    fecha_registro timestamp(6) without time zone NOT NULL,
    nombre character varying(100) NOT NULL,
    telefono character varying(20)
);


ALTER TABLE public.visitantes OWNER TO postgres;

--
-- Name: visitantes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.visitantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.visitantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: admin_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin_users (id, activo, nombre, password, username) FROM stdin;
\.


--
-- Data for Name: administradores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.administradores (id, activo, apellido, contrasena, correo, fecha_actualizacion, fecha_creacion, nombre, usuario) FROM stdin;
1	t	Administrador	$2a$10$1zRWJV0zTwihdd.37i5phuwQoVUaZ/eT9KfSifidipF9vHaSCc9Xq	superadmin@pharma911.com	\N	2026-08-26 09:18:17.91202	Super	superadmin
2	t	Reyes Montoya	$2a$10$sBNA2BWrPrivr2T84qsRfuC97MHrdBdV4lWITeNR1M2xbz4ZLBvBC	j.reyes@pharma911.com	\N	2026-08-26 09:18:18.004444	Dr. Jorge	j.reyes
3	t	Sánchez	$2a$10$wHdmDfOyldId4H/7hlVKPOo/EXqcc3KwrmWaSPqT684QsDSMr4ece	a.sanchez@pharma911.com	\N	2026-08-26 09:18:18.099439	Ing. Andrea	a.sanchez
\.


--
-- Data for Name: auditoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auditoria (id, accion, descripcion, fecha, administrador_id) FROM stdin;
\.


--
-- Data for Name: departamentos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departamentos (id, activo, descripcion, fecha_actualizacion, fecha_creacion, nombre) FROM stdin;
1	t	Líneas de manufactura y envasado estéril	\N	2026-08-26 09:18:17.55253	Producción
2	t	Laboratorios de microbiología y físico-química	\N	2026-08-26 09:18:17.552572	Control de Calidad
3	t	Área de bioseguridad y formulación avanzada	\N	2026-08-26 09:18:17.552594	Investigación y Desarrollo
4	t	Muelle de carga y bodega de materias primas	\N	2026-08-26 09:18:17.552612	Almacén y Logística
5	t	Gerencia de planta y oficinas corporativas	\N	2026-08-26 09:18:17.552629	Administración
6	t	Talento humano, bienestar y capacitación	\N	2026-08-26 09:18:17.552646	Recursos Humanos
\.


--
-- Data for Name: empleados; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empleados (id, acceso_permitido, activo, apellido, cargo, correo, documento, fecha_actualizacion, fecha_creacion, nombre, departamento_id) FROM stdin;
1	t	t	Mendoza	Operador de Envasado Estéril	c.mendoza@pharma911.com	1020304050	\N	2026-07-27 09:18:18.319958	Carlos	1
2	t	t	Ramos	Analista Microbiológica Senior	e.ramos@pharma911.com	2030405060	\N	2026-08-01 09:18:18.320058	Dra. Elena	2
3	t	t	Castro	Especialista en Bioseguridad N3	j.castro@pharma911.com	3040506070	\N	2026-08-06 09:18:18.320085	Dr. Julián	3
4	t	t	Morales	Supervisor de Recepción	m.morales@pharma911.com	4050607080	\N	2026-08-11 09:18:18.320108	Martín	4
5	t	t	Valencia	Coordinadora de Auditoría BPF	d.valencia@pharma911.com	5060708090	\N	2026-08-16 09:18:18.320128	Diana	5
6	f	f	Gómez	Técnica de Muestreo	l.gomez@pharma911.com	6070809010	\N	2026-08-18 09:18:18.320148	Laura	2
7	t	t	Pineda	Técnico de Mantenimiento Electromecánico	a.pineda@pharma911.com	7080901020	\N	2026-08-21 09:18:18.320168	Andrés	1
8	t	t	Herrera	Especialista en Capacitación BPF	s.herrera@pharma911.com	8090102030	\N	2026-08-23 09:18:18.320189	Sofía	6
\.


--
-- Data for Name: historial_acceso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.historial_acceso (id, acceso_permitido, fecha_ingreso, fecha_salida, observaciones, empleado_id) FROM stdin;
\.


--
-- Data for Name: intento_acceso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.intento_acceso (id, exito, acceso_date, message, empleado_id) FROM stdin;
1	t	2026-08-26 05:18:18.454832	Acceso autorizado: Esclusa 1 Producción A	1
2	t	2026-08-26 06:18:18.454892	Acceso autorizado: Lector Biométrico Lab QC	2
3	f	2026-08-26 07:18:18.454916	Acceso denegado: Credencial inactiva en sistema	6
4	t	2026-08-26 08:18:18.454938	Acceso autorizado: Lab B-2 Bioequivalencia	3
5	t	2026-08-26 08:33:18.454958	Acceso autorizado: Torniquete Muelle de Carga	4
6	t	2026-08-26 08:58:18.454984	Acceso autorizado: Torniquete Entrada Principal	1
7	t	2026-08-25 09:18:18.455024	Acceso autorizado: Entrada Principal	5
8	t	2026-08-24 09:18:18.455043	Acceso autorizado: Lab QC	2
9	t	2026-08-23 09:18:18.455062	Acceso autorizado: Lab B-2	3
\.


--
-- Data for Name: visitantes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.visitantes (id, activo, apellido, correo, documento, empresa, fecha_actualizacion, fecha_registro, nombre, telefono) FROM stdin;
\.


--
-- Name: admin_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_users_id_seq', 1, false);


--
-- Name: administradores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.administradores_id_seq', 3, true);


--
-- Name: auditoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auditoria_id_seq', 1, false);


--
-- Name: departamentos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departamentos_id_seq', 6, true);


--
-- Name: empleados_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empleados_id_seq', 8, true);


--
-- Name: historial_acceso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.historial_acceso_id_seq', 1, false);


--
-- Name: intento_acceso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.intento_acceso_id_seq', 9, true);


--
-- Name: visitantes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.visitantes_id_seq', 1, false);


--
-- Name: admin_users admin_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT admin_users_pkey PRIMARY KEY (id);


--
-- Name: administradores administradores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT administradores_pkey PRIMARY KEY (id);


--
-- Name: auditoria auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id);


--
-- Name: departamentos departamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT departamentos_pkey PRIMARY KEY (id);


--
-- Name: empleados empleados_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleados
    ADD CONSTRAINT empleados_pkey PRIMARY KEY (id);


--
-- Name: historial_acceso historial_acceso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historial_acceso
    ADD CONSTRAINT historial_acceso_pkey PRIMARY KEY (id);


--
-- Name: intento_acceso intento_acceso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.intento_acceso
    ADD CONSTRAINT intento_acceso_pkey PRIMARY KEY (id);


--
-- Name: admin_users uk3fgxk4ewgaxgtgvqwb1jjudj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_users
    ADD CONSTRAINT uk3fgxk4ewgaxgtgvqwb1jjudj6 UNIQUE (username);


--
-- Name: empleados uk5l7j8378rxvcv2yq3kic8f17i; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleados
    ADD CONSTRAINT uk5l7j8378rxvcv2yq3kic8f17i UNIQUE (documento);


--
-- Name: administradores uk7316o5l539qjngk19733jdgxm; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT uk7316o5l539qjngk19733jdgxm UNIQUE (correo);


--
-- Name: administradores uk7tuduhy89ravpc4ejxkwj0p1q; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT uk7tuduhy89ravpc4ejxkwj0p1q UNIQUE (usuario);


--
-- Name: departamentos uk9vfgma390a16fkev3ryhnyrvh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT uk9vfgma390a16fkev3ryhnyrvh UNIQUE (nombre);


--
-- Name: empleados ukh1yoynfig4dn2d3vff3luwyj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleados
    ADD CONSTRAINT ukh1yoynfig4dn2d3vff3luwyj UNIQUE (correo);


--
-- Name: visitantes uksqf3u08u7gckbbspf4bcvb83j; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visitantes
    ADD CONSTRAINT uksqf3u08u7gckbbspf4bcvb83j UNIQUE (documento);


--
-- Name: visitantes visitantes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.visitantes
    ADD CONSTRAINT visitantes_pkey PRIMARY KEY (id);


--
-- Name: empleados fk1dvvcamb3oxb2d9xqd9taug0u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleados
    ADD CONSTRAINT fk1dvvcamb3oxb2d9xqd9taug0u FOREIGN KEY (departamento_id) REFERENCES public.departamentos(id);


--
-- Name: auditoria fkfr32wmcc0k8j57hncu839s40d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT fkfr32wmcc0k8j57hncu839s40d FOREIGN KEY (administrador_id) REFERENCES public.administradores(id);


--
-- Name: intento_acceso fkjioykfn6vybhxvtb76i78w61v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.intento_acceso
    ADD CONSTRAINT fkjioykfn6vybhxvtb76i78w61v FOREIGN KEY (empleado_id) REFERENCES public.empleados(id);


--
-- Name: historial_acceso fkrdi8amrcmv1eyne9c5bxwkjl2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historial_acceso
    ADD CONSTRAINT fkrdi8amrcmv1eyne9c5bxwkjl2 FOREIGN KEY (empleado_id) REFERENCES public.empleados(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict McdhWlN8BZ2uhSymDhaPmVuzeQB2h6ZBr1pZxKSQbxtR5pbHgONC7GFo8BRsSgQ

