--
-- PostgreSQL database dump
--

\restrict ZIfMatesaGFr11Dg9moCf3BFrV4AQgqutJrfDpniqghhlJnruVvvhfhLNQ9MV6s

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.historial_acceso DROP CONSTRAINT IF EXISTS fkrdi8amrcmv1eyne9c5bxwkjl2;
ALTER TABLE IF EXISTS ONLY public.intento_acceso DROP CONSTRAINT IF EXISTS fkjioykfn6vybhxvtb76i78w61v;
ALTER TABLE IF EXISTS ONLY public.auditoria DROP CONSTRAINT IF EXISTS fkfr32wmcc0k8j57hncu839s40d;
ALTER TABLE IF EXISTS ONLY public.departamentos DROP CONSTRAINT IF EXISTS fk_departamentos_administrador;
ALTER TABLE IF EXISTS ONLY public.empleados DROP CONSTRAINT IF EXISTS fk1dvvcamb3oxb2d9xqd9taug0u;
DROP INDEX IF EXISTS public.unico_empleados_documento;
DROP INDEX IF EXISTS public.unico_empleados_correo;
DROP INDEX IF EXISTS public.unico_departamentos_nombre;
DROP INDEX IF EXISTS public.unico_administradores_usuario;
DROP INDEX IF EXISTS public.unico_administradores_correo;
DROP INDEX IF EXISTS public.indice_intento_acceso_fecha;
DROP INDEX IF EXISTS public.indice_intento_acceso_empleado_fecha;
DROP INDEX IF EXISTS public.indice_intento_acceso_empleado;
DROP INDEX IF EXISTS public.indice_historial_acceso_empleado;
DROP INDEX IF EXISTS public.indice_empleados_nombre;
DROP INDEX IF EXISTS public.indice_empleados_departamento;
DROP INDEX IF EXISTS public.indice_empleados_apellido;
DROP INDEX IF EXISTS public.indice_auditoria_administrador;
ALTER TABLE IF EXISTS ONLY public.intento_acceso DROP CONSTRAINT IF EXISTS intento_acceso_pkey;
ALTER TABLE IF EXISTS ONLY public.historial_acceso DROP CONSTRAINT IF EXISTS historial_acceso_pkey;
ALTER TABLE IF EXISTS ONLY public.empleados DROP CONSTRAINT IF EXISTS empleados_pkey;
ALTER TABLE IF EXISTS ONLY public.departamentos DROP CONSTRAINT IF EXISTS departamentos_pkey;
ALTER TABLE IF EXISTS ONLY public.auditoria DROP CONSTRAINT IF EXISTS auditoria_pkey;
ALTER TABLE IF EXISTS ONLY public.administradores DROP CONSTRAINT IF EXISTS administradores_pkey;
DROP TABLE IF EXISTS public.intento_acceso;
DROP TABLE IF EXISTS public.historial_acceso;
DROP TABLE IF EXISTS public.empleados;
DROP TABLE IF EXISTS public.departamentos;
DROP TABLE IF EXISTS public.auditoria;
DROP TABLE IF EXISTS public.administradores;
-- *not* dropping schema, since initdb creates it
--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: administradores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administradores (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    apellido character varying(100) NOT NULL,
    contrasena character varying(255) NOT NULL,
    correo character varying(255) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(100) NOT NULL,
    usuario character varying(100) NOT NULL,
    rol character varying(30) NOT NULL
);


--
-- Name: administradores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.administradores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administradores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria (
    id bigint NOT NULL,
    accion character varying(100) NOT NULL,
    descripcion character varying(500),
    fecha timestamp(6) without time zone NOT NULL,
    administrador_id bigint NOT NULL
);


--
-- Name: auditoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departamentos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departamentos (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    descripcion character varying(255),
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(100) NOT NULL,
    capacidad_maxima integer,
    codigo character varying(20),
    nivel_restriccion character varying(20),
    responsable character varying(100),
    administrador_id bigint
);


--
-- Name: departamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: empleados; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.empleados (
    id bigint NOT NULL,
    acceso_permitido boolean NOT NULL,
    activo boolean NOT NULL,
    apellido character varying(100) NOT NULL,
    cargo character varying(100) NOT NULL,
    correo character varying(255) NOT NULL,
    documento character varying(20) NOT NULL,
    fecha_actualizacion timestamp(6) without time zone,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(100) NOT NULL,
    departamento_id bigint NOT NULL
);


--
-- Name: empleados_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.empleados ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empleados_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historial_acceso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historial_acceso (
    id bigint NOT NULL,
    acceso_permitido boolean NOT NULL,
    fecha_ingreso timestamp(6) without time zone NOT NULL,
    fecha_salida timestamp(6) without time zone,
    observaciones character varying(255),
    empleado_id bigint NOT NULL
);


--
-- Name: historial_acceso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.historial_acceso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_acceso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: intento_acceso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.intento_acceso (
    id bigint NOT NULL,
    exito boolean NOT NULL,
    fecha_acceso timestamp(6) without time zone NOT NULL,
    mensaje character varying(255),
    empleado_id bigint,
    documento_intentado character varying(20)
);


--
-- Name: intento_acceso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.intento_acceso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.intento_acceso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: administradores; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.administradores (id, activo, apellido, contrasena, correo, fecha_actualizacion, fecha_creacion, nombre, usuario, rol) FROM stdin;
1	t	Administrador	$2a$10$LQdZDwcLZaBxypbdoK82zO8rnF.kglh9jjk/h3a6UcUYWG8jvYGdm	superadmin@pharma911.com	\N	2026-08-26 09:18:17.91202	Super	superadmin	SUPER_ADMIN
3	t	Sánchez	$2a$10$3kWC81pN2UxNPTFCU5PGCunUVxsaPO55n8XJCurzwGDjmNxPlWm2K	a.sanchez@pharma911.com	\N	2026-08-26 09:18:18.099439	Ing. Andrea	a.sanchez	ADMIN_SISTEMAS
\.


--
-- Data for Name: auditoria; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auditoria (id, accion, descripcion, fecha, administrador_id) FROM stdin;
\.


--
-- Data for Name: departamentos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.departamentos (id, activo, descripcion, fecha_actualizacion, fecha_creacion, nombre, capacidad_maxima, codigo, nivel_restriccion, responsable, administrador_id) FROM stdin;
1	t	Líneas de manufactura y envasado estéril	2026-09-03 17:16:04.411499	2026-08-26 09:18:17.55253	Producción 777	50	DPT-001	MEDIA	Dr. paco	1
3	t	Área de bioseguridad y formulación avanzada	2026-09-03 20:53:54.872401	2026-08-26 09:18:17.552594	Investigación y Desarrollo	1	DPT-003	CRITICA	MIJITO	1
4	t	Muelle de carga y bodega de materias primas	2026-09-03 20:54:11.417721	2026-08-26 09:18:17.552612	Almacén y Logística	50	DPT-004	MEDIA	MIJITO	1
5	f	Gerencia de planta y oficinas corporativas	2026-09-03 20:54:22.35296	2026-08-26 09:18:17.552629	Administración	\N	\N	\N	\N	1
2	t	Laboratorios de microbiología y físico-química	2026-09-03 20:54:38.28913	2026-08-26 09:18:17.552572	Control de Calidad	\N	\N	\N	\N	1
6	t	Talento humano, bienestar y capacitación	2026-09-03 20:54:40.767902	2026-08-26 09:18:17.552646	Recursos Humanos	\N	\N	\N	\N	1
\.


--
-- Data for Name: empleados; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.empleados (id, acceso_permitido, activo, apellido, cargo, correo, documento, fecha_actualizacion, fecha_creacion, nombre, departamento_id) FROM stdin;
3	t	t	Castro	Especialista en Bioseguridad N3	j.castro@pharma911.com	3040506070	\N	2026-08-06 09:18:18.320085	Dr. Julián	3
5	t	t	Valencia	Coordinadora de Auditoría BPF	d.valencia@pharma911.com	5060708090	\N	2026-08-16 09:18:18.320128	Diana	5
6	f	f	Gómez	Técnica de Muestreo	l.gomez@pharma911.com	6070809010	\N	2026-08-18 09:18:18.320148	Laura	2
7	t	t	Pineda	Técnico de Mantenimiento Electromecánico	a.pineda@pharma911.com	7080901020	\N	2026-08-21 09:18:18.320168	Andrés	1
1	f	t	Mendoza	Operador de Envasado Estéril	c.mendoza@pharma911.com	1020304050	2026-09-03 17:16:55.642846	2026-07-27 09:18:18.319958	Carlos	1
9	t	t	Ruiz Gómez	Analista de Control de Calidad N2	camila.ruiz@pharma911.com	910203040	\N	2026-09-03 19:17:24.622485	María Fernanda	2
10	t	t	Salazar Mora	Técnico en Esterilización de Equipos	je.salazar@pharma911.com	910203041	\N	2026-09-03 19:17:24.715741	Jorge Enrique	2
11	t	t	Ortega Pineda	Supervisora de Producción Estéril	le.ortega@pharma911.com	910203042	\N	2026-09-03 19:17:24.756083	Lucía	2
12	t	t	Cárdenas Ríos	Operador de Llenado y Sellado	af.cardenas@pharma911.com	910203043	\N	2026-09-03 19:17:24.788459	Andrés Felipe	2
13	t	t	Mejía Ospina	Microbiólogo de Planta	v.mejia@pharma911.com	910203044	\N	2026-09-03 19:17:24.821695	Valentina	2
14	t	t	Alvarez Duarte	Coordinador de Logística de Almacén	r.alvarez@pharma911.com	910203045	\N	2026-09-03 19:17:24.855275	Ricardo	2
15	t	t	Nieto Cifuentes	Especialista en Asuntos Regulatorios	pa.nieto@pharma911.com	910203046	\N	2026-09-03 19:17:24.888065	Paula Andrea	2
16	t	t	Restrepo Vargas	Técnico de Calibración de Instrumentos	c.restrepo@pharma911.com	910203047	\N	2026-09-03 19:17:24.930219	Camilo	2
17	t	t	Zapata Quintero	Analista de Documentación BPF	d.zapata@pharma911.com	910203048	\N	2026-09-03 19:17:24.972339	Daniela	2
18	t	t	Herrón Agudelo	Auditor Interno de Calidad	f.herron@pharma911.com	910203049	\N	2026-09-03 19:17:25.013571	Felipe	2
4	f	t	Morales	Supervisor de Recepción	m.morales@pharma911.com	4050607080	2026-09-03 19:50:18.61626	2026-08-11 09:18:18.320108	Martín	4
2	t	t	Ramos	LO QUE QUIERA	e.ramos@pharma911.com	2030405060	2026-09-03 20:39:14.710381	2026-08-01 09:18:18.320058	lo que sea	2
8	f	t	Herrera	Especialista en Capacitación BPF	s.herrera@pharma911.com	8090102030	2026-09-03 20:41:13.057823	2026-08-23 09:18:18.320189	Sofía	6
\.


--
-- Data for Name: historial_acceso; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.historial_acceso (id, acceso_permitido, fecha_ingreso, fecha_salida, observaciones, empleado_id) FROM stdin;
\.


--
-- Data for Name: intento_acceso; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.intento_acceso (id, exito, fecha_acceso, mensaje, empleado_id, documento_intentado) FROM stdin;
9	t	2026-08-23 09:18:18.455062	Acceso autorizado: Lab B-2	3	3040506070
4	t	2026-08-26 08:18:18.454938	Acceso autorizado: Lab B-2 Bioequivalencia	3	3040506070
7	t	2026-08-25 09:18:18.455024	Acceso autorizado: Entrada Principal	5	5060708090
3	f	2026-08-26 07:18:18.454916	Acceso denegado: Credencial inactiva en sistema	6	6070809010
14	t	2026-09-03 20:30:00.541266	Acceso permitido, bienvenido	7	7080901020
11	f	2026-09-03 20:29:45.649023	Acceso no permitido	1	1020304050
6	t	2026-08-26 08:58:18.454984	Acceso autorizado: Torniquete Entrada Principal	1	1020304050
1	t	2026-08-26 05:18:18.454832	Acceso autorizado: Esclusa 1 Producción A	1	1020304050
10	t	2026-09-03 17:17:24.998288	Acceso permitido, bienvenido	4	4050607080
5	t	2026-08-26 08:33:18.454958	Acceso autorizado: Torniquete Muelle de Carga	4	4050607080
12	t	2026-09-03 20:29:54.060159	Acceso permitido, bienvenido	2	2030405060
8	t	2026-08-24 09:18:18.455043	Acceso autorizado: Lab QC	2	2030405060
2	t	2026-08-26 06:18:18.454892	Acceso autorizado: Lector Biométrico Lab QC	2	2030405060
13	t	2026-09-03 20:29:57.578347	Acceso permitido, bienvenido	8	8090102030
\.


--
-- Name: administradores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.administradores_id_seq', 3, true);


--
-- Name: auditoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auditoria_id_seq', 1, false);


--
-- Name: departamentos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.departamentos_id_seq', 7, true);


--
-- Name: empleados_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.empleados_id_seq', 18, true);


--
-- Name: historial_acceso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.historial_acceso_id_seq', 1, false);


--
-- Name: intento_acceso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.intento_acceso_id_seq', 14, true);


--
-- Name: administradores administradores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administradores
    ADD CONSTRAINT administradores_pkey PRIMARY KEY (id);


--
-- Name: auditoria auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id);


--
-- Name: departamentos departamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT departamentos_pkey PRIMARY KEY (id);


--
-- Name: empleados empleados_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empleados
    ADD CONSTRAINT empleados_pkey PRIMARY KEY (id);


--
-- Name: historial_acceso historial_acceso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_acceso
    ADD CONSTRAINT historial_acceso_pkey PRIMARY KEY (id);


--
-- Name: intento_acceso intento_acceso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intento_acceso
    ADD CONSTRAINT intento_acceso_pkey PRIMARY KEY (id);


--
-- Name: indice_auditoria_administrador; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX indice_auditoria_administrador ON public.auditoria USING btree (administrador_id);


--
-- Name: indice_empleados_apellido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX indice_empleados_apellido ON public.empleados USING btree (apellido);


--
-- Name: indice_empleados_departamento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX indice_empleados_departamento ON public.empleados USING btree (departamento_id);


--
-- Name: indice_empleados_nombre; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX indice_empleados_nombre ON public.empleados USING btree (nombre);


--
-- Name: indice_historial_acceso_empleado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX indice_historial_acceso_empleado ON public.historial_acceso USING btree (empleado_id);


--
-- Name: indice_intento_acceso_empleado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX indice_intento_acceso_empleado ON public.intento_acceso USING btree (empleado_id);


--
-- Name: indice_intento_acceso_empleado_fecha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX indice_intento_acceso_empleado_fecha ON public.intento_acceso USING btree (empleado_id, fecha_acceso);


--
-- Name: indice_intento_acceso_fecha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX indice_intento_acceso_fecha ON public.intento_acceso USING btree (fecha_acceso);


--
-- Name: unico_administradores_correo; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unico_administradores_correo ON public.administradores USING btree (correo) WHERE activo;


--
-- Name: unico_administradores_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unico_administradores_usuario ON public.administradores USING btree (usuario) WHERE activo;


--
-- Name: unico_departamentos_nombre; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unico_departamentos_nombre ON public.departamentos USING btree (nombre) WHERE activo;


--
-- Name: unico_empleados_correo; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unico_empleados_correo ON public.empleados USING btree (correo) WHERE activo;


--
-- Name: unico_empleados_documento; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unico_empleados_documento ON public.empleados USING btree (documento) WHERE activo;


--
-- Name: empleados fk1dvvcamb3oxb2d9xqd9taug0u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empleados
    ADD CONSTRAINT fk1dvvcamb3oxb2d9xqd9taug0u FOREIGN KEY (departamento_id) REFERENCES public.departamentos(id);


--
-- Name: departamentos fk_departamentos_administrador; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT fk_departamentos_administrador FOREIGN KEY (administrador_id) REFERENCES public.administradores(id);


--
-- Name: auditoria fkfr32wmcc0k8j57hncu839s40d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT fkfr32wmcc0k8j57hncu839s40d FOREIGN KEY (administrador_id) REFERENCES public.administradores(id);


--
-- Name: intento_acceso fkjioykfn6vybhxvtb76i78w61v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.intento_acceso
    ADD CONSTRAINT fkjioykfn6vybhxvtb76i78w61v FOREIGN KEY (empleado_id) REFERENCES public.empleados(id);


--
-- Name: historial_acceso fkrdi8amrcmv1eyne9c5bxwkjl2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_acceso
    ADD CONSTRAINT fkrdi8amrcmv1eyne9c5bxwkjl2 FOREIGN KEY (empleado_id) REFERENCES public.empleados(id);


--
-- PostgreSQL database dump complete
--

\unrestrict ZIfMatesaGFr11Dg9moCf3BFrV4AQgqutJrfDpniqghhlJnruVvvhfhLNQ9MV6s

